### PR TITLE
Pde

### PR DESCRIPTION
**Pull request by nicnys-8**
This code probably belongs in a completely separate branch for now (perhaps named pde).

### CODE REVIEW

**Comment by jronnberg** [comment]
Should I do a 
 git commit -a --amend -s
and force push to our pde branch to solve this error?
Will this pull-request pick up that I do a forced push?

**Comment by tsvetlin** [comment]
Leave it as it is. Meanwhile you can fix that Eclipse error on your side.

**Comment by jerkerdelsing** [comment]
To speed up the adoption of Nicklas as a committer I like to see the pdf code in a branch, e.g. named pdf,  of the core-java-spring repository.

I think this is an important thing to solve ASAP.


Jerker
====================
Professor Jerker Delsing
Lulea University of Technology
EISLAB
97187 Lulea
Sweden
email: ***@***.******@***.***>
phone: 0046706261931
http://www.ltu.se/eislab

On 24 Mar 2021, at 12:49, Tanyi Szvetlin ***@***.******@***.***>> wrote:



Leave it as it is. Meanwhile you can fix that Eclipse error on your side.

**Comment by tsvetlin** [comment]
Hello!

We've finished the first round of code review, please fix the found issues. See below. 

Coding Convention:

* don't use wildcards (*) in imports
* use final whenever possible
* avoid using var
* do not use string literals (except in log messages, exceptions, descriptions, etc), use constants instead
* do not use public fields (with the exception of final primitives, or maybe Strings), see for example Alarm class
* enum values should be UPPER_CASE (see AlarmCause)
* public methods should check its input before using it

For example

public List<Alarm> getActiveAlarmData(AlarmCause cause) {
       return activeAlarms.stream()
           .filter(alarm -> cause.equals(alarm.cause))
           .collect(Collectors.toList());
   }

this one throws NullPointerException if cause is null

Potentional issue:

* PDE uses kalix library and sometimes using the DTO classes from the library. We will change some DTO in the core-java-spring repo (for example SystemDTO class has a new metadata field), and the kalix's DTO class is no longer represents perfectly the entities (for example ProviderDescription class). So after some necessary changes in the mandatory core systems, we should contact the maintainer of the kalix library to do the same on their end.


Issues:

* In application.properties there is a reference for a certificate file and a truststore file, but I don't find them
* In RuleCreator.createRule()

       final Map<String, String> providerMetadata = provider.portMetadata(producerPortName);

If I understand correctly, this line merges the provider's (as system) metadata with the service's metadata, then create a rule using this as provider's metadata. I think this is wrong. According to the flexible store proposal, there is a separate field for service metadata


* In AlarmManager.clearAlarm()

alarm.clearedAt = Instant.now();
alarm.updatedAt = Instant.now();

lines can cause that the two fields contain different timestamps

Fix: (only the timestamp problem, the direct access of fields is still not a good practice in general)

alarm.clearedAt = Instant.now();
alarm.updatedAt = alarm.clearedAt;

* In FileRuleStore.writeRules()

writer can stay open if a write() call throws IOException => use try-with-resources statement or simply a finally block

* In SqlRuleStore

hard coded user and password is not a good idea.

* In FilePsStore.write()

out can stay open

* In PdeMonitorService

private final static int fetchInfoInterval = 6000; // Milliseconds
private final static int pingInterval = 10000; // Milliseconds

these shouldn't be hard coded values, but parameters coming from the property file

* In PingTask

   private void ping(ServiceDescription service) {
       final var address = service.provider().socketAddress();
       final String providerName = service.provider().name();
       httpClient
           .send(address,
               new HttpClientRequest()
                   .method(HttpMethod.GET)
                   .uri(service.uri() + "/ping")
                   .header("accept",
                       "application/json"))
           .ifSuccess(result -> {
               logger.info("Successfully pinged system '" + providerName + "'.");
               alarmManager.clearSystemInactive(providerName);
           })
           .onFailure(e -> {
               logger.warn("Failed to ping system '" + providerName + "'.", e);
               alarmManager.raiseSystemInactive(providerName);
           });
   }

	This ping is problematic. Creating for every service another to ping it (service.uri() + "/ping") is currently not a requirement in Arrowhead. Not even our core systems do that (but they have an /echo service). So in the documentation you must express that every PDE-compatible system should work like this. The same is true to the RetrieveMonitorInfoTask as well.

* In DTOWriter

	can't close the resource (OutputStream).

**Comment by jerkerdelsing** [comment]
Szvetlin

To we don’t need a code review to get it into a branch of the master of core-jav-srping?!

Jerker
====================
Professor Jerker Delsing
Lulea University of Technology
EISLAB
97187 Lulea
Sweden
email: ***@***.******@***.***>
phone: 0046706261931
http://www.ltu.se/eislab

On 24 Mar 2021, at 13:24, Tanyi Szvetlin ***@***.******@***.***>> wrote:



Hello!

We've finished the first round of code review, please fix the found issues. See below.

Coding Convention:

  *   don't use wildcards (*) in imports
  *   use final whenever possible
  *   avoid using var
  *   do not use string literals (except in log messages, exceptions, descriptions, etc), use constants instead
  *   do not use public fields (with the exception of final primitives, or maybe Strings), see for example Alarm class
  *   enum values should be UPPER_CASE (see AlarmCause)
  *   public methods should check its input before using it

For example

public List getActiveAlarmData(AlarmCause cause) {
return activeAlarms.stream()
.filter(alarm -> cause.equals(alarm.cause))
.collect(Collectors.toList());
}

this one throws NullPointerException if cause is null

Potentional issue:

  *   PDE uses kalix library and sometimes using the DTO classes from the library. We will change some DTO in the core-java-spring repo (for example SystemDTO class has a new metadata field), and the kalix's DTO class is no longer represents perfectly the entities (for example ProviderDescription class). So after some necessary changes in the mandatory core systems, we should contact the maintainer of the kalix library to do the same on their end.

Issues:

  *   In application.properties there is a reference for a certificate file and a truststore file, but I don't find them

  *   In RuleCreator.createRule()

 final Map<String, String> providerMetadata = provider.portMetadata(producerPortName);


If I understand correctly, this line merges the provider's (as system) metadata with the service's metadata, then create a rule using this as provider's metadata. I think this is wrong. According to the flexible store proposal, there is a separate field for service metadata

  *   In AlarmManager.clearAlarm()

alarm.clearedAt = Instant.now();
alarm.updatedAt = Instant.now();

lines can cause that the two fields contain different timestamps

Fix: (only the timestamp problem, the direct access of fields is still not a good practice in general)

alarm.clearedAt = Instant.now();
alarm.updatedAt = alarm.clearedAt;

  *   In FileRuleStore.writeRules()

writer can stay open if a write() call throws IOException => use try-with-resources statement or simply a finally block

  *   In SqlRuleStore

hard coded user and password is not a good idea.

  *   In FilePsStore.write()

out can stay open

  *   In PdeMonitorService

private final static int fetchInfoInterval = 6000; // Milliseconds
private final static int pingInterval = 10000; // Milliseconds

these shouldn't be hard coded values, but parameters coming from the property file

  *   In PingTask

private void ping(ServiceDescription service) {
final var address = service.provider().socketAddress();
final String providerName = service.provider().name();
httpClient
.send(address,
new HttpClientRequest()
.method(HttpMethod.GET)
.uri(service.uri() + "/ping")
.header("accept",
"application/json"))
.ifSuccess(result -> {
logger.info<http://logger.info>("Successfully pinged system '" + providerName + "'.");
alarmManager.clearSystemInactive(providerName);
})
.onFailure(e -> {
logger.warn("Failed to ping system '" + providerName + "'.", e);
alarmManager.raiseSystemInactive(providerName);
});
}

This ping is problematic. Creating for every service another to ping it (service.uri() + "/ping") is currently not a requirement in Arrowhead. Not even our core systems do that (but they have an /echo service). So in the documentation you must express that every PDE-compatible system should work like this. The same is true to the RetrieveMonitorInfoTask as well.

  *   In DTOWriter

can't close the resource (OutputStream).

**Comment by tsvetlin** [comment]
They want to merge this into the "development" branch. It's a no go. Let me see if I can create a new branch for them and redirect the PR. 

image

**Comment by jerkerdelsing** [comment]
Thanks

Jerker
====================
Professor Jerker Delsing
Lulea University of Technology
EISLAB
97187 Lulea
Sweden
email: ***@***.******@***.***>
phone: 0046706261931
http://www.ltu.se/eislab

On 24 Mar 2021, at 13:30, Tanyi Szvetlin ***@***.******@***.***>> wrote:



They want to merge this into the "development" branch. It's a no go. Let me see if I can create a new branch for them and redirect the PR.

[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F15650896%2F112310582-079aa580-8ca5-11eb-90ea-09cd624c37df.png&data=04%7C01%7C%7Cea120eb40c804acd4a3808d8eec097cf%7C5453408ba6cd4c1e8b1018b500fb544e%7C1%7C0%7C637521858258137773%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eeujihDsm%2Bu83ic5ybB6KIZo32WbYvsBZnYMVafHGqA%3D&reserved=0>

**Comment by tsvetlin** [comment]
Jerker, could you please not use the "email" reply feature in the future. It really clutters the whole discussion with spam.

**Pull request merged**
