### PR TITLE
Add Docker image containing all Core system

### PR DESCRIPTION
**Pull request by emanuelpalm**
An attempt at contributing to #175.

To make it apparent how much RAM overhead is reduced by gathering all systems into a single container, please look at the following screen dumps from the Ubuntu Monitor application.

__No systems started (baseline)__

I have a browser, an IDE, an editor and some other minor applications running on my machine. At this point no Arrowhead systems are running. The sudden slope early in the graph shows the point where I turned off an application. The stable line after it is what should be considered the baseline.

no-systems

__One Docker container per system (default GC)__

Here, the following 5 systems are running, each in their own Docker container: ServiceRegistry, Orchestrator, Authorization, Gatekeeper and Gateway. The EventHandler is __not__ included in this comparison. Given that the baseline is 5 GB and the average system memory consumption is 9.3 GB, the consumption per system is (9.3-5)/5 ≈ 0.9 GB on average.

one-container-per-system

__One Docker container for all systems (default GC)__

one-container-for-all-systems-nojvmargs

Here, the same 5 systems are running inside the one image part of this PR. This time the memory consumption is (8.7-5)/5 ≈ 0,7 GB on average.

__One Docker container for all systems (-XX:+UseSerialGC)__

I tried to reduce RAM usage via GC tuning, and settled on the following flags after trying several confiurations: `-XX:+UseSerialGC -Xmx1G -Xms32m`. This time the memory consumption is (6,9-5)/5 ≈ 0,4 GB on average.

one-container-for-all-systems

__Conclusions__

It seems like gathering the systems into a single container reduced memory overhead with about 600MB, or 100-200MB per system, which is not a bad result. Switching from the default GC to the serial one (which has worse performance in terms of execution through-put) lead to a saving of about 200-300 MB per systems, which is very good.

__I would argue that it is a good idea to allow users of the one-system-per-container images you have already created to supply their own JVM flags.__

### CODE REVIEW

**Comment by emanuelpalm** [comment]
Note that during all of the benchmark the systems were pretty much idle.

**Comment by tsvetlin** [comment]
It's a great option to have this option. Thank you for your contribution!

**Comment by tsvetlin** [comment]
Could you please write a few sentences into the main README file to the docker section?https://github.com/arrowhead-f/core-java-spring#quickstart_docker 
After that I'll merge it!

**Comment by emanuelpalm** [comment]
@tsvetlin I'm leaving it to you guys to figure out the conflicts. Apparently, I was working from an older commit.

**Comment by tsvetlin** [comment]
I'll help you out with that

**Pull request merged**
