### PR TITLE
Implement toString methods in DTOs

### PR DESCRIPTION
**Pull request by BlackRose01**
Implement a toString-method to all DTOs. Already implemented methods were overwritten to be uniform. All toString-methods uses the GSON package from Google. Now all objects will return a JSON-compliant string.

The following toString-methods from this classes were overwritten:
* CertificateCreationResponseDTO
* DeviceQueryFormDTO
* DeviceQueryResultDTO
* DeviceRegistryOnboardingResponseDTO
* DeviceRegistryOnboardingWithCsrRequestDTO
* DeviceRegistryOnboardingWithNameRequestDTO
* DeviceRegistryRequestDTO
* DeviceRegistryResponseDTO
* DeviceRequestDTO
* DeviceResponseDTO
* ErrorMessageDTO
* KeyPairDTO
* OnboardingResponseDTO
* OnboardingWithCsrRequestDTO
* OnboardingWithNameRequestDTO
* PreferredProviderDataDTO
* ServiceEndpoint
* ServiceRegistryRequestDTO
* ServiceRegistryResponseDTO
* SystemQueryFormDTO
* SystemQueryResultDTO
* SystemRegistryOnboardingResponseDTO
* SystemRegistryOnboardingWithCsrRequestDTO
* SystemRegistryOnboardingWithNameRequestDTO
* SystemRegistryRequestDTO
* SystemRegistryResponseDTO
* SystemRequestDTO
* SystemResponseDTO

### CODE REVIEW

**Comment by borditamas** [comment]
Hi,

we have discussed the usage of Gson and came to the standpoint, that Jackson which is already part of the project (coming with Spring) would be a better choice. No need for additional dependency and the following code works fine:

```
@Override
public String toString() {
	try {
		return new ObjectMapper().writeValueAsString(this);
	} catch (final JsonProcessingException ex) {
		return "toString failure";
	}
}
```

**Comment by BlackRose01** [comment]
Sure. That's also a good possibility. Do I need to change something or create a new pull-request?

**Comment by borditamas** [comment]
You can use this PR just commit the changes whenever you have time for it.

**Comment by BlackRose01** [comment]
Hello,

I created a new Pull Request for the toString implementation. It has a new Branch with another name so that the GSON implementation is still available. So I think we can close this PR now.

New Pull Request: [https://github.com/arrowhead-f/core-java-spring/pull/267](https://github.com/arrowhead-f/core-java-spring/pull/267)

**Pull request closed without merging**
