### PR TITLE
Hawkbit configuration manager

### PR DESCRIPTION
**Pull request by rbocsi**

### CODE REVIEW

**Comment by LuLeRoemer** [comment]
Thanks for the PR

**Comment by LuLeRoemer** [comment]
Thanks for fixing the log4j vulnerability. I had some problems testing the changes last week, receiving an error from the service registry during startup. I guess it might be due to the fact that I was not using v4.4.0 of the core systems. I'll test the changes again with v4.4.0 end of the week.

**Review by LuLeRoemer — APPROVED** [review]
After testing the functionality with the newest version of the Arrowhead Core Systems (4.4.0) everything worked as expected.

**Comment by tsvetlin** [comment]
Sorry for the delay @LuLeRoemer. Merging Now.

**Pull request merged**
